// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/fairs": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fairs"
                ],
                "summary": "List fairs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/fair.Fair"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fairs"
                ],
                "summary": "Create fairs",
                "parameters": [
                    {
                        "description": "body raw",
                        "name": "raw",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fair.CreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fair.Fair"
                        }
                    }
                }
            }
        },
        "/fairs/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fairs"
                ],
                "summary": "Find fair",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fair.Fair"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fairs"
                ],
                "summary": "Update fair",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body raw",
                        "name": "raw",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/fair.UpdateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/fair.Fair"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fairs"
                ],
                "summary": "Delete fair",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/fairs/{name}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "fairs"
                ],
                "summary": "List fairs by Name",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/fair.Fair"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "fair.CreateDTO": {
            "type": "object",
            "required": [
                "areap",
                "cod_dist",
                "cod_sub_pref",
                "district",
                "fair_name",
                "lat",
                "long",
                "neighborhood",
                "number",
                "record",
                "reference",
                "region_5",
                "region_8",
                "setcens",
                "street"
            ],
            "properties": {
                "areap": {
                    "type": "string"
                },
                "cod_dist": {
                    "type": "integer"
                },
                "cod_sub_pref": {
                    "type": "integer"
                },
                "district": {
                    "type": "string"
                },
                "fair_name": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "long": {
                    "type": "number"
                },
                "neighborhood": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "record": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "region_5": {
                    "type": "string"
                },
                "region_8": {
                    "type": "string"
                },
                "setcens": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        },
        "fair.Fair": {
            "type": "object",
            "properties": {
                "areap": {
                    "type": "string"
                },
                "cod_dist": {
                    "type": "integer"
                },
                "cod_sub_pref": {
                    "type": "integer"
                },
                "district": {
                    "type": "string"
                },
                "fair_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lat": {
                    "type": "number"
                },
                "long": {
                    "type": "number"
                },
                "neighborhood": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "record": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "region_5": {
                    "type": "string"
                },
                "region_8": {
                    "type": "string"
                },
                "setcens": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        },
        "fair.UpdateDTO": {
            "type": "object",
            "required": [
                "areap",
                "cod_dist",
                "cod_sub_pref",
                "district",
                "fair_name",
                "lat",
                "long",
                "neighborhood",
                "number",
                "record",
                "reference",
                "region_5",
                "region_8",
                "setcens",
                "street"
            ],
            "properties": {
                "areap": {
                    "type": "string"
                },
                "cod_dist": {
                    "type": "integer"
                },
                "cod_sub_pref": {
                    "type": "integer"
                },
                "district": {
                    "type": "string"
                },
                "fair_name": {
                    "type": "string"
                },
                "lat": {
                    "type": "number"
                },
                "long": {
                    "type": "number"
                },
                "neighborhood": {
                    "type": "string"
                },
                "number": {
                    "type": "string"
                },
                "record": {
                    "type": "string"
                },
                "reference": {
                    "type": "string"
                },
                "region_5": {
                    "type": "string"
                },
                "region_8": {
                    "type": "string"
                },
                "setcens": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
